---
title: "Baseline calculations"
author: "Peter Kamerman"
date: "Last knitted: `r format(Sys.Date(), '%d %B %Y')`"
---

```{r set_up, include = FALSE}
# Load packages
library(tidyverse)
library(spatstat)

# Set options
knitr::opts_chunk$set(fig.path = 'figures/baseline-calculations/')
```

----

# Pain intensity threshold values

- Data source: Finnerup et al 2015, Appendix 4.

- All numeric values used (after removing duplicates).

- All values converted to a values out of 10.

```{r thresholds}
cut_off <- c(5, 4, 4, 2, 4, 3, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
             4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
             4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 3, 4, 
             4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 4, 4, 4, 3, 5, 4, 4, 4, 5, 5,
             4, 4, 5, 3, 4, 4, 4, 5, 4, 3, 3, 3, 3, 3, 3, 3, 4, 7, 5, 4, 3, 2,
             3, 4, 4, 2.5, 2.5, 4, 4, 4, 4, 5, 4, 4, 8, 4, 4, 4, 5, 3, 4, 4, 4)

ggplot(data = data.frame(cutoff = cut_off)) +
    aes(cutoff) +
    geom_histogram(binwidth = 1,
                   fill = '#FFFFFF',
                   colour = '#000000') +
    labs(x = 'Baseline pain threshold value (0-10 rating scale)',
         y = 'Count') +
    scale_x_continuous(breaks = 2:8) +
    theme_bw(base_size = 18)

summary(cut_off)
length(cut_off)
data.frame(cutoff = cut_off) %>% 
    group_by(cutoff) %>% 
    summarise(count = n(),
              percent = round(100 * (count/length(cut_off)), 1)) %>% 
    knitr::kable(., caption = 'Summary of threshold values')
```

----

# Explore baseline pain intensity data

## Import data

- Data source: Finnerup et al 2015, Appendix 4,

```{r import data}
data <- read_csv('data/baseline-data.csv')
```

## Explore data 

### Median
```{r median_explore}
data %>% 
    filter(mean_or_median == 'median') %>% 
    summarise(max = max(value),
              min = min(value)) %>% 
    knitr::kable(., caption = 'Range of median values')
```

### Mean
```{r mean_explore}
data %>% 
    filter(mean_or_median == 'mean') %>% 
    summarise(max = max(value),
              min = min(value)) %>% 
    knitr::kable(., caption = 'Range of mean values')

data %>% 
    filter(mean_or_median == 'mean') %>% 
    ggplot(data = .) +
    aes(value) +
    geom_histogram(binwidth = 1,
                   fill = '#FFFFFF',
                   colour = '#000000') +
    labs(subtitle = 'Histogram of mean values (binwidth = 1)',
         x = 'Sample mean (0-10 rating scale)',
         y = 'Count') +
    scale_x_continuous(limits = c(0, 10),
                       breaks = 0:10) +
    theme_bw(base_size = 18)
```

### SD
```{r sd_explore}
data %>% 
    filter(!is.na(sd)) %>% 
    summarise(max = max(sd),
              min = min(sd)) %>% 
    knitr::kable(., caption = 'Range of SD values')

data %>% 
    filter(!is.na(sd)) %>% 
    ggplot(data = .) +
    aes(sd) +
    geom_histogram(binwidth = 0.25,
                   fill = '#FFFFFF',
                   colour = '#000000') +
    labs(subtitle = 'Histogram of SD values (binwidth = 0.25)',
         x = 'Sample SDs',
         y = 'Count') +
    theme_bw(base_size = 18)
```

----

# Weighted medians 

- Three studies, four median values.

- Hahn_2004(active), Hahn_2004(placebo), Yuen_2002, Low_1995

```{r median}
# Process data
median <- data %>% 
    filter(included_in_analysis == 'yes') %>% 
    filter(mean_or_median == 'median') %>% 
    # Calculate total sample size
    mutate(total_sample = sum(sample_size)) %>% 
    # Calculate weights
    mutate(weights = sample_size / total_sample)
    
## Weighted median
weighted.median(x = median$value, 
                w = median$weights)
```

----

# Pooled mean

- Formula sourced from: https://www.ncbi.nlm.nih.gov/books/NBK56512/

```{r pooled_mean}
# Process data
mean <- data %>% 
    filter(included_in_analysis == 'yes') %>% 
    filter(mean_or_median == 'mean') %>% 
    # Multiply mean by the sample size
    mutate(mean_by_n = value * sample_size) 

# Pooled mean
sum(mean$mean_by_n) / sum(mean$sample_size)
```

----

# Pooled SD

- Formula sourced from: https://www.ncbi.nlm.nih.gov/books/NBK56512/

```{r pooled_sd}
# Process data
sd <- data %>% 
    filter(included_in_analysis == 'yes') %>% 
    filter(mean_or_median == 'mean') %>% 
    filter(!is.na(sd)) %>% 
    # Square the SD
    mutate(SD_squared = sd^2) %>% 
    # Calculate sample size -1
    mutate(n_minus_1 = sample_size - 1) %>% 
    # Get the number of groups
    mutate(k = length(unique(.$authors))) %>% 
    # Calculate (n-1)SD^2
    mutate(numerator = SD_squared * n_minus_1)

# Pooled SD
sqrt(sum(sd$numerator) / (sum(sd$sample_size) - sd$k[[1]]))
```

----

# Session information
```{r session_info}
sessionInfo()
```