---
title: "Regression to the mean modeling"
subtitle: "Regression curves: mean pain rating of 6.2 (SD: 1.7)"
author: "Peter Kamerman"
date: "Last knitted: `r format(Sys.Date(), '%d %B %Y')`"
---

```{r include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(MASS)
library(MBESS)
library(car)
library(smatr)

# Set ggplot theme
theme_set(new = theme_bw(base_size = 20)) 
theme_update(legend.text = element_text(size = 14),
             axis.text = element_text(colour = '#000000',
                                      size = 20),
             axis.title = element_text(size = 20),
             panel.grid = element_blank(),
             plot.caption = element_text(size = 12),
             plot.title = element_text(size = 20),
             plot.subtitle = element_text(size = 16))

# Output options
if(!dir.exists('figures')){
  dir.create('figures')  
} 

if(!dir.exists('figures/r-to-m')){
  dir.create('figures/r-to-m')  
} 

knitr::opts_chunk$set(fig.height = 7,
               fig.width = 7,
               fig.path = 'figures/r-to-m/')
```

----

# Premise

Unless the correlation between two sequential measurements is 1, there should be a "flattening" of the relationship between the two, and greater "scatter". This "flattening" and greater "scatter" of the relationship has important implications for the use of cut-off criteria for study inclusion.

This script demonstrates the "flattening" of, and increase in "scatter" in, the relationship between two sequential pain measurements, both with mean = 6.2 and SD = 1.7 (typical baseline values for placebo groups in neuropathic pain RCTs without a cut-off inclusion citerion), over a range of correlational structures: r = 1.0, 0.8, 0.5, and 0.2.

----

# Generate 2x2 covariance matrices 

Generate covariance matrices using an SD of 1.7 and correlation of 1.0, 0.8, 0.5, and 0.2.

```{r cov_matrix}
# Correlation matrices
cor_10 <- matrix(c(1, 1, 1, 1), ncol = 2)
cor_08 <- matrix(c(1, 0.8, 0.8, 1), ncol = 2)
cor_05 <- matrix(c(1, 0.5, 0.5, 1), ncol = 2)
cor_02 <- matrix(c(1, 0.2, 0.2, 1), ncol = 2)

# Standard deviation
std <- c(1.7, 1.7)

# Covariance matrices
cov_10 <- cor2cov(cor.mat = cor_10,
                  sd = std)
cov_10
cov_08 <- cor2cov(cor.mat = cor_08,
                  sd = std)
cov_08
cov_05 <- cor2cov(cor.mat = cor_05,
                  sd = std)
cov_05
cov_02 <- cor2cov(cor.mat = cor_02,
                  sd = std)
cov_02
```

----

# Mean = 6.2, SD = 1.7, r = 1.0

## Generate and summarise data

### Base data

```{r 10_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data (1000 pairs)
cor_10.base <- as.data.frame(mvrnorm(n = 1000, mu = c(6.2, 6.2), Sigma = cov_10))

# Plot base data
ggplot(data = cor_10.base) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_10.base$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_10.base$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_10.base$V1, 
                              cor_10.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.base$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_10.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.base$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_10.base$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_10.base$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_10.base$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_10.base$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_10.base$V1), 2)}")) +
    labs(title = 'A: Unconstained',
         caption = 'Parameters: Mean = 6.2, SD = 1.7, r = 1.0') +
    scale_y_continuous(limits = c(-5, 15)) +
    scale_x_continuous(limits = c(-5, 15)) +
    theme(plot.caption = element_text(size = 14))

# Linear regression
summary(lm(V2 ~ V1, data = cor_10.base))
Confint(lm(V2 ~ V1, data = cor_10.base))
```

### Constrain values to 0-10 range

```{r 10_constrained}
# Process data
cor_10.constrained <- cor_10.base %>%
    mutate(V1 = case_when(
               V1 < 1 ~ 1,
               V1 > 10 ~ 10,
               TRUE ~ V1)) %>% 
    mutate(V2 = case_when(
               V2 < 0 ~ 0,
               V2 > 10 ~ 10,
               TRUE ~ V2)) %>% 
    mutate(group = 'No threshold')

# Plot processed data
ggplot(data = cor_10.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_10.constrained$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_10.constrained$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_10.constrained$V1, 
                                         cor_10.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.constrained$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_10.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.constrained$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_10.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_10.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5, 
             label = str_glue("Mean = {round(mean(cor_10.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_10.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_10.constrained$V1), 2)}")) +
    labs(title = 'B: Constrained (0-10 range)',
         caption = 'Parameters: Mean = 6.2, SD = 1.7, r = 1.0') +
    scale_y_continuous(limits = c(-5, 15)) +
    scale_x_continuous(limits = c(-5, 15)) +
    theme(plot.caption = element_text(size = 14))
  
# Linear regression
summary(lm(V2 ~ V1, data = cor_10.constrained))
Confint(lm(V2 ~ V1, data = cor_10.constrained))
```

----

# Mean = 6.2, SD = 1.7, r = 0.8

## Generate and summarise data

### Base data

```{r 08_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data (1000 pairs)
cor_08.base <- as.data.frame(mvrnorm(n = 1000, mu = c(6.2, 6.2), Sigma = cov_08))

# Plot base data
ggplot(data = cor_08.base) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_08.base$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_08.base$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_08.base$V1, 
                              cor_08.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.base$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_08.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.base$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_08.base$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_08.base$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_08.base$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_08.base$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_08.base$V1), 2)}")) +
    labs(title = 'A: Unconstained',
         caption = 'Parameters: Mean = 6.2, SD = 1.7, r = 0.8') +
    scale_y_continuous(limits = c(-5, 15)) +
    scale_x_continuous(limits = c(-5, 15)) +
    theme(plot.caption = element_text(size = 14))

# Linear regression
summary(lm(V2 ~ V1, data = cor_08.base))
Confint(lm(V2 ~ V1, data = cor_08.base))
```

### Constrain values to 0-10 range

```{r 08_constrained}
# Process data
cor_08.constrained <- cor_08.base %>%
    mutate(V1 = case_when(
               V1 < 1 ~ 1,
               V1 > 10 ~ 10,
               TRUE ~ V1)) %>% 
    mutate(V2 = case_when(
               V2 < 0 ~ 0,
               V2 > 10 ~ 10,
               TRUE ~ V2)) %>% 
    mutate(group = 'No threshold')

# Plot processed data
ggplot(data = cor_08.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_08.constrained$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_08.constrained$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_08.constrained$V1, 
                              cor_08.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.constrained$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_08.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.constrained$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_08.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_08.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5, 
             label = str_glue("Mean = {round(mean(cor_08.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_08.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_08.constrained$V1), 2)}")) +
    labs(title = 'B: Constrained (0-10 range)',
         caption = 'Parameters: Mean = 6.2, SD = 1.7, r = 0.8') +
    scale_y_continuous(limits = c(-5, 15)) +
    scale_x_continuous(limits = c(-5, 15)) +
    theme(plot.caption = element_text(size = 14))
  
# Linear regression
summary(lm(V2 ~ V1, data = cor_08.constrained))
Confint(lm(V2 ~ V1, data = cor_08.constrained))
## Slope different to 1
```

----

# Mean = 6.2, SD = 1.7, r = 0.5

## Generate and summarise data

### Base data

```{r 05_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data (1000 pairs)
cor_05.base <- as.data.frame(mvrnorm(n = 1000, mu = c(6.2, 6.2), Sigma = cov_05))

# Plot base data
ggplot(data = cor_05.base) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_05.base$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_05.base$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_05.base$V1, 
                              cor_05.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.base$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_05.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.base$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_05.base$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_05.base$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_05.base$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_05.base$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_05.base$V1), 2)}")) +
    labs(title = 'A: Unconstained',
         caption = 'Parameters: Mean = 6.2, SD = 1.7, r = 0.5') +
    scale_y_continuous(limits = c(-5, 15)) +
    scale_x_continuous(limits = c(-5, 15)) +
    theme(plot.caption = element_text(size = 14))

# Linear regression
summary(lm(V2 ~ V1, data = cor_05.base))
Confint(lm(V2 ~ V1, data = cor_05.base))
```

### Constrain values to 0-10 range

```{r 05_constrained}
# Process data
cor_05.constrained <- cor_05.base %>%
    mutate(V1 = case_when(
               V1 < 1 ~ 1,
               V1 > 10 ~ 10,
               TRUE ~ V1)) %>% 
    mutate(V2 = case_when(
               V2 < 0 ~ 0,
               V2 > 10 ~ 10,
               TRUE ~ V2)) %>% 
    mutate(group = 'No threshold')

# Plot processed data
ggplot(data = cor_05.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_05.constrained$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_05.constrained$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_05.constrained$V1, 
                              cor_05.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.constrained$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_05.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.constrained$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_05.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_05.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5, 
             label = str_glue("Mean = {round(mean(cor_05.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_05.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_05.constrained$V1), 2)}")) +
    labs(title = 'B: Constrained (0-10 range)',
         caption = 'Parameters: Mean = 6.2, SD = 1.7, r = 0.5') +
    scale_y_continuous(limits = c(-5, 15)) +
    scale_x_continuous(limits = c(-5, 15)) +
    theme(plot.caption = element_text(size = 14))
  
# Linear regression
summary(lm(V2 ~ V1, data = cor_05.constrained))
Confint(lm(V2 ~ V1, data = cor_05.constrained))
```

----

# Mean = 6.2, SD = 1.7, r = 0.2

## Generate and summarise data

### Base data

```{r 02_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data
cor_02.base <- as.data.frame(mvrnorm(n = 1000, mu = c(6.2, 6.2), Sigma = cov_02))

# Plot base data
ggplot(data = cor_02.base) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_02.base$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_02.base$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_02.base$V1, 
                              cor_02.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.base$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_02.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.base$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_02.base$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_02.base$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_02.base$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_02.base$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_02.base$V1), 2)}")) +
    labs(title = 'A: Unconstained',
         caption = 'Parameters: Mean = 6.2, SD = 1.7, r = 0.2') +
    scale_y_continuous(limits = c(-5, 15)) +
    scale_x_continuous(limits = c(-5, 15)) +
    theme(plot.caption = element_text(size = 14))

# Linear regression
summary(lm(V2 ~ V1, data = cor_02.base))
Confint(lm(V2 ~ V1, data = cor_02.base))
```

### Constrain values to 0-10 range

```{r 02_constrained}
# Process data
cor_02.constrained <- cor_02.base %>%
    mutate(V1 = case_when(
               V1 < 1 ~ 1,
               V1 > 10 ~ 10,
               TRUE ~ V1)) %>% 
    mutate(V2 = case_when(
               V2 < 0 ~ 0,
               V2 > 10 ~ 10,
               TRUE ~ V2)) %>% 
    mutate(group = 'No threshold')

# Plot processed data
ggplot(data = cor_02.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_02.constrained$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_02.constrained$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_02.constrained$V1, 
                              cor_02.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.constrained$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_02.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.constrained$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_02.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_02.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5, 
             label = str_glue("Mean = {round(mean(cor_02.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_02.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_02.constrained$V1), 2)}")) +
    labs(title = 'B: Constrained (0-10 range)',
         caption = 'Parameters: Mean = 6.2, SD = 1.7, r = 0.2') +
    scale_y_continuous(limits = c(-5, 15)) +
    scale_x_continuous(limits = c(-5, 15)) +
    theme(plot.caption = element_text(size = 14))
  
# Linear regression
summary(lm(V2 ~ V1, data = cor_02.constrained))
Confint(lm(V2 ~ V1, data = cor_02.constrained))
```

----

# Session information 

```{r}
sessionInfo()
```

