---
title: "Regression to the mean modeling"
subtitle: "Mean NRS pain rating of 6.2 at 0.8 correlation"
author: "Peter Kamerman"
date: "Last knitted: `r format(Sys.Date(), '%d %B %Y')`"
---

```{r include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(MASS)
library(rcompanion)
library(ggExtra)
library(MBESS)
library(knitr)

# Set ggplot theme
theme_set(new = theme_bw(base_size = 18))

# Palette
pal <- c('#2678B2', '#FD7F28')

# Output options
if(!dir.exists('figures')){
  dir.create('figures')  
} 

if(!dir.exists('figures/six.two_08')){
  dir.create('figures/six.two_08')  
} 

opts_chunk$set(fig.height = 8,
               fig.width = 8,
               fig.path = 'figures/six.two_08/')
```

# Generate 2x2 covariance matrix 

Generate a covariance matrix using an SD of 1.2, 1.7, and 2.2, and correlation of 0.8.

```{r cov_matrix}
cor <- matrix(c(1, 0.8, 0.8, 1), ncol = 2)
std_1 <- c(1.2, 1.2)
std_2 <- c(1.7, 1.7)
std_3 <- c(2.2, 2.2)
cov_1 <- cor2cov(cor.mat = cor,
                 sd = std_1)
cov_1
cov_2 <- cor2cov(cor.mat = cor,
                 sd = std_2)
cov_2
cov_3 <- cor2cov(cor.mat = cor,
                 sd = std_3)
cov_3
```

----

# Mean = 6.2, SD = 1.2, cor = 0.8

## Generate and summarise data

### Base data

```{r one_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data
six_1.base <- as.data.frame(mvrnorm(n = 150, mu = c(6.2, 6.2), Sigma = cov_1))

# Plot base data
ggMarginal(ggplot(data = six_1.base) +
               aes(x = V1, y = V2) + 
               geom_point() + 
               geom_hline(yintercept = mean(six_1.base$V2), colour = 'red') +
               geom_vline(xintercept = mean(six_1.base$V1), colour = 'red') +
               geom_hline(yintercept = 0, linetype = 2) +
               geom_hline(yintercept = 10, linetype = 2) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_vline(xintercept = 10, linetype = 2) +
               annotate(geom = 'text', x = -5, y = 15, hjust = 0,
                        label = str_glue("r = {round(cor(six_1.base$V1, six_1.base$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 7.5, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_1.base$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 8.5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_1.base$V2),2)}")) +
               annotate(geom = 'text', x = 6.5, y = -4, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_1.base$V1), 2)}")) +
               annotate(geom = 'text', x = 6.5, y = -5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_1.base$V1), 2)}")) +
               labs(subtitle = 'Mean = 6.2, SD = 1.2, cor = 0.8') +
               scale_y_continuous(limits = c(-5, 15)) +
               scale_x_continuous(limits = c(-5, 15)) +
               theme(panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)))

# Linear regression
summary(lm(V2 ~ V1, data = six_1.base))
```

### Constrain values to 0-10 range

```{r one_constrained}
# Process data
six_1 <- six_1.base %>%
    mutate(V1 = case_when(
               V1 < 1 ~ 1,
               V1 > 10 ~ 10,
               TRUE ~ V1)) %>% 
    mutate(V2 = case_when(
               V2 < 0 ~ 0,
               V2 > 10 ~ 10,
               TRUE ~ V2)) %>% 
    mutate(group = 'No cut-off')

# Plot processed data
ggMarginal(ggplot(data = six_1) +
               aes(x = V1, y = V2) + 
               geom_point() + 
               geom_hline(yintercept = mean(six_1$V2), colour = 'red') +
               geom_vline(xintercept = mean(six_1$V1), colour = 'red') +
               geom_hline(yintercept = 0, linetype = 2) +
               geom_hline(yintercept = 10, linetype = 2) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_vline(xintercept = 10, linetype = 2) +
               annotate(geom = 'text', x = -5, y = 15, hjust = 0,
                        label = str_glue("r = {round(cor(six_1$V1, six_1$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 7.5, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_1$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 6.5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_1$V2),2)}")) +
               annotate(geom = 'text', x = 6.5, y = -4, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_1$V1), 2)}")) +
               annotate(geom = 'text', x = 6.5, y = -5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_1$V1), 2)}")) +
               labs(subtitle = 'Mean = 6.2, SD = 1.2 (constrained), cor = 0.8') +
               scale_y_continuous(limits = c(-5, 15)) +
               scale_x_continuous(limits = c(-5, 15)) +
               theme(panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)))

# Linear regression
summary(lm(V2 ~ V1, data = six_1))
```

## Model mean of V1 with increasing V1 cut-offs from 0 to 5 

```{r one_cutoffV1V1}
# Extract visit 1 data 
six_1V1 <- six_1$V1

# Generate a vector of cut-off values to iterate over
cutoff <- 0:5

# Generate a vector of V1 means at each V1 cut-off
six_1V1.shift <- sapply(cutoff, function(x){mean(six_1V1[six_1V1 > x])})

# Calculate deviation 
(six_1V1.df <- data.frame(cutoff = cutoff,
                          mean = six_1V1.shift) %>% 
        mutate(deviation = mean - mean(six_1V1)))

# Plot data
ggplot(data = six_1V1.df) +
    aes(x = cutoff, y = mean, ymin = mean(six_1V1), ymax = mean) +
    geom_ribbon(alpha = 0.6) +
    geom_point(size = 3) +
    geom_line(size = 1) +
    geom_text(aes(label = round(mean, 2)), nudge_y = 1) +
    scale_y_continuous(limits = c(0, 10),
                       breaks = c(0, 2, 4, 6, 8, 10)) +
    labs(subtitle = 'Shift in V1 mean with increasing V1 NRS cut-off value',
         x = 'NRS cut-off',
         y = 'NRS mean score') +
    theme(panel.grid = element_blank(),
          plot.subtitle = element_text(size = 16))
```

## Model mean of V2 with increasing V1 cut-offs from 0 to 5 

```{r one_cutoffV1V2}
# Extract visit 2 data 
six_1V2 <- six_1$V2

# Generate a vector of cut-off values to iterate over
cutoff <- 0:5

# Generate a vector of V2 means at each V1 cut-off
six_1V2.shift <- map_dbl(.x = cutoff,
                          ~ six_1 %>% 
                              filter(V1 > .x) %>% 
                              .$V2 %>% 
                              mean(.))

# Calculate deviation
(six_1V2.df <- data.frame(cutoff = cutoff,
                           mean = six_1V2.shift) %>% 
        mutate(deviation = mean - mean(six_1V2)))

# Plot data
ggplot(data = six_1V2.df) +
    aes(x = cutoff, y = mean, ymin = mean(six_1V2), ymax = mean) +
    geom_ribbon(alpha = 0.6) +
    geom_point(size = 3) +
    geom_line(size = 1) +
    geom_text(aes(label = round(mean, 2)), nudge_y = 1) +
    scale_y_continuous(limits = c(0, 10),
                       breaks = c(0, 2, 4, 6, 8, 10)) +
    labs(subtitle = 'Shift in V2 mean with increasing V1 NRS cut-off value',
         x = 'NRS cut-off',
         y = 'NRS mean score') + 
    theme(panel.grid = element_blank(),
          plot.subtitle = element_text(size = 16))
```

## Placebo response

### threshold: 0

```{r one_threshold0}
# Process data
placebo_1.0 <- six_1 %>% 
    filter(V1 >= 0) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_1.0,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_1.0[, 1:3] %>% 
               bind_rows(six_1) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_1,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_1.0,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_1$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_1.0$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_hline(yintercept = mean(six_1$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_1.0$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.5, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_1V1.df$deviation[4], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_1V2.df$deviation[4], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.2, cor = 0.8; Cut-off: 0') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```


### threshold: 3

```{r one_threshold3}
# Process data
placebo_1.3 <- six_1 %>% 
    filter(V1 >= 3) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_1.3,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_1.3[, 1:3] %>% 
               bind_rows(six_1) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_1,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_1.3,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_1$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_1.3$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 3, linetype = 2) +
               geom_hline(yintercept = mean(six_1$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_1.3$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.5, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_1V1.df$deviation[4], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_1V2.df$deviation[4], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.2, cor = 0.8; Cut-off: 3') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

### threshold: 4

```{r one_threshold4}
# Process that data
placebo_1.4 <- six_1 %>% 
    filter(V1 >= 4) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Set seed
set.seed(2019)

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_1.4,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_1.4[, 1:3] %>% 
               bind_rows(six_1) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_1,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_1.4,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_1$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_1.4$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 4, linetype = 2) +
               geom_hline(yintercept = mean(six_1$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_1.4$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.5, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_1V1.df$deviation[5], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_1V2.df$deviation[5], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.2, cor = 0.8; Cut-off: 4') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

### threshold: 5

```{r one_threshold5}
# Process that data 
placebo_1.5 <- six_1 %>% 
    filter(V1 >= 5) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Set seed
set.seed(2019)

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_1.5,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_1.5[, 1:3] %>% 
               bind_rows(six_1) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_1,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_1.5,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_1$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_1.5$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 5, linetype = 2) +
               geom_hline(yintercept = mean(six_1$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_1.5$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.5, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_1V1.df$deviation[6], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_1V2.df$deviation[6], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.2, cor = 0.8; Cut-off: 5') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

----

# Mean = 6.2, SD = 1.7, cor = 0.8

## Generate and summarise data

### Base data

```{r two_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data
six_2.base <- as.data.frame(mvrnorm(n = 150, mu = c(6.2, 6.2), Sigma = cov_2))

# Plot base data
ggMarginal(ggplot(data = six_2.base) +
               aes(x = V1, y = V2) + 
               geom_point() + 
               geom_hline(yintercept = mean(six_2.base$V2), colour = 'red') +
               geom_vline(xintercept = mean(six_2.base$V1), colour = 'red') +
               geom_hline(yintercept = 0, linetype = 2) +
               geom_hline(yintercept = 10, linetype = 2) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_vline(xintercept = 10, linetype = 2) +
               annotate(geom = 'text', x = -5, y = 15, hjust = 0,
                        label = str_glue("r = {round(cor(six_2.base$V1, six_2.base$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 7.5, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_2.base$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 6.5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_2.base$V2),2)}")) +
               annotate(geom = 'text', x = 6.5, y = -4, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_2.base$V1), 2)}")) +
               annotate(geom = 'text', x = 6.5, y = -5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_2.base$V1), 2)}")) +
               labs(subtitle = 'Mean = 6.2, SD = 1.7, cor = 0.8') +
               scale_y_continuous(limits = c(-5, 15)) +
               scale_x_continuous(limits = c(-5, 15)) +
               theme(panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)))

# Linear regression
summary(lm(V2 ~ V1, data = six_2.base))
```

### Constrain values to 0-10 range

```{r two_constrained}
# Process data
six_2 <- six_2.base %>%
    mutate(V1 = case_when(
               V1 < 1 ~ 1,
               V1 > 10 ~ 10,
               TRUE ~ V1)) %>% 
    mutate(V2 = case_when(
               V2 < 0 ~ 0,
               V2 > 10 ~ 10,
               TRUE ~ V2)) %>% 
    mutate(group = 'No cut-off')

# Plot processed data
ggMarginal(ggplot(data = six_2) +
               aes(x = V1, y = V2) + 
               geom_point() + 
               geom_hline(yintercept = mean(six_2$V2), colour = 'red') +
               geom_vline(xintercept = mean(six_2$V1), colour = 'red') +
               geom_hline(yintercept = 0, linetype = 2) +
               geom_hline(yintercept = 10, linetype = 2) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_vline(xintercept = 10, linetype = 2) +
               annotate(geom = 'text', x = -5, y = 15, hjust = 0,
                        label = str_glue("r = {round(cor(six_2$V1, six_2$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 7.5, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_2$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 6.5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_2$V2),2)}")) +
               annotate(geom = 'text', x = 6.5, y = -4, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_2$V1), 2)}")) +
               annotate(geom = 'text', x = 6.5, y = -5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_2$V1), 2)}")) +
               labs(subtitle = 'Mean = 6.2, SD = 1.7 (constrained), cor = 0.8') +
               scale_y_continuous(limits = c(-5, 15)) +
               scale_x_continuous(limits = c(-5, 15)) +
               theme(panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)))

# Linear regression
summary(lm(V2 ~ V1, data = six_2))
```

## Model mean of V1 with increasing V1 cut-offs from 0 to 5 

```{r two_cutoffV1V1}
# Extract visit 1 data 
six_2V1 <- six_2$V1

# Generate a vector of cut-off values to iterate over
cutoff <- 0:5

# Generate a vector of V1 means at each V1 cut-off
six_2V1.shift <- sapply(cutoff, function(x){mean(six_2V1[six_2V1 > x])})

# Calculate deviation 
(six_2V1.df <- data.frame(cutoff = cutoff,
                           mean = six_2V1.shift) %>% 
        mutate(deviation = mean - mean(six_2V1)))

# Plot data
ggplot(data = six_2V1.df) +
    aes(x = cutoff, y = mean, ymin = mean(six_2V1), ymax = mean) +
    geom_ribbon(alpha = 0.6) +
    geom_point(size = 3) +
    geom_line(size = 1) +
    geom_text(aes(label = round(mean, 2)), nudge_y = 1) +
    scale_y_continuous(limits = c(0, 10),
                       breaks = c(0, 2, 4, 6, 8, 10)) +
    labs(subtitle = 'Shift in V1 mean with increasing V1 NRS cut-off value',
         x = 'NRS cut-off',
         y = 'NRS mean score') +
    theme(panel.grid = element_blank(),
          plot.subtitle = element_text(size = 16))
```

## Model mean of V2 with increasing V1 cut-offs from 0 to 5 

```{r two_cutoffV1V2}
# Extract visit 2 data 
six_2V2 <- six_2$V2

# Generate a vector of cut-off values to iterate over
cutoff <- 0:5

# Generate a vector of V2 means at each V1 cut-off
six_2V2.shift <- map_dbl(.x = cutoff,
                          ~ six_2 %>% 
                              filter(V1 > .x) %>% 
                              .$V2 %>% 
                              mean(.))

# Calculate deviation
(six_2V2.df <- data.frame(cutoff = cutoff,
                           mean = six_2V2.shift) %>% 
        mutate(deviation = mean - mean(six_2V2)))

# Plot data
ggplot(data = six_2V2.df) +
    aes(x = cutoff, y = mean, ymin = mean(six_2V2), ymax = mean) +
    geom_ribbon(alpha = 0.6) +
    geom_point(size = 3) +
    geom_line(size = 1) +
    geom_text(aes(label = round(mean, 2)), nudge_y = 1) +
    scale_y_continuous(limits = c(0, 10),
                       breaks = c(0, 2, 4, 6, 8, 10)) +
    labs(subtitle = 'Shift in V2 mean with increasing V1 NRS cut-off value',
         x = 'NRS cut-off',
         y = 'NRS mean score') + 
    theme(panel.grid = element_blank(),
          plot.subtitle = element_text(size = 16))
```

## Placebo response

### threshold: 0

```{r two_threshold0}
# Process data
placebo_2.0 <- six_2 %>% 
    filter(V1 >= 0) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_2.0,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_2.0[, 1:3] %>% 
               bind_rows(six_2) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_2,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_2.0,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_2$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_2.0$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_hline(yintercept = mean(six_2$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_2.0$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.5, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_2V1.df$deviation[4], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_2V2.df$deviation[4], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.2, cor = 0.8; Cut-off: 0') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

### threshold: 3

```{r two_threshold3}
# Process data
placebo_2.3 <- six_2 %>% 
    filter(V1 >= 3) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Set seed
set.seed(2019)

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_2.3,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_2.3[, 1:3] %>% 
               bind_rows(six_2) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_2,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_2.3,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_2$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_2.3$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 3, linetype = 2) +
               geom_hline(yintercept = mean(six_2$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_2.3$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.5, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_2V1.df$deviation[4], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_2V2.df$deviation[4], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.7, cor = 0.8; Cut-off: 3') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

### threshold: 4

```{r two_threshold4}
# Process that data
placebo_2.4 <- six_2 %>% 
    filter(V1 >= 4) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Set seed
set.seed(2019)

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_2.4,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_2.4[, 1:3] %>% 
               bind_rows(six_2) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_2,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_2.4,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_2$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_2.4$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 4, linetype = 2) +
               geom_hline(yintercept = mean(six_2$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_2.4$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.8, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_2V1.df$deviation[5], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_2V2.df$deviation[5], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.7, cor = 0.8; Cut-off: 4') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

### threshold: 5

```{r two_threshold5}
# Process that data 
placebo_2.5 <- six_2 %>% 
    filter(V1 >= 5) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Set seed
set.seed(2019)

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_2.5,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_2.5[, 1:3] %>% 
               bind_rows(six_2) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_2,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_2.5,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_2$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_2.5$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 5, linetype = 2) +
               geom_hline(yintercept = mean(six_2$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_2.5$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 7, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_2V1.df$deviation[6], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_2V2.df$deviation[6], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.7, cor = 0.8; Cut-off: 5') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

----

# Mean = 6.2, SD = 2.2, cor = 0.8

## Generate and summarise data

### Base data

```{r three_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data
six_3.base <- as.data.frame(mvrnorm(n = 150, mu = c(6.2, 6.2), Sigma = cov_3))

# Plot base data
ggMarginal(ggplot(data = six_3.base) +
               aes(x = V1, y = V2) + 
               geom_point() + 
               geom_hline(yintercept = mean(six_3.base$V2), colour = 'red') +
               geom_vline(xintercept = mean(six_3.base$V1), colour = 'red') +
               geom_hline(yintercept = 0, linetype = 2) +
               geom_hline(yintercept = 10, linetype = 2) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_vline(xintercept = 10, linetype = 2) +
               annotate(geom = 'text', x = -5, y = 15, hjust = 0,
                        label = str_glue("r = {round(cor(six_3.base$V1, six_3.base$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 7.5, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_3.base$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 6.5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_3.base$V2),2)}")) +
               annotate(geom = 'text', x = 6.5, y = -4, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_3.base$V1), 2)}")) +
               annotate(geom = 'text', x = 6.5, y = -5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_3.base$V1), 2)}")) +
               labs(subtitle = 'Mean = 6.2, SD = 2.2, cor = 0.8') +
               scale_y_continuous(limits = c(-5, 15)) +
               scale_x_continuous(limits = c(-5, 15)) +
               theme(panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)))

# Linear regression
summary(lm(V2 ~ V1, data = six_3.base))
```

### Constrain values to 0-10 range

```{r three_constrained}
# Process data
six_3 <- six_3.base %>%
    mutate(V1 = case_when(
               V1 < 1 ~ 1,
               V1 > 10 ~ 10,
               TRUE ~ V1)) %>% 
    mutate(V2 = case_when(
               V2 < 0 ~ 0,
               V2 > 10 ~ 10,
               TRUE ~ V2)) %>% 
    mutate(group = 'No cut-off')

# Plot processed data
ggMarginal(ggplot(data = six_3) +
               aes(x = V1, y = V2) + 
               geom_point() + 
               geom_hline(yintercept = mean(six_3$V2), colour = 'red') +
               geom_vline(xintercept = mean(six_3$V1), colour = 'red') +
               geom_hline(yintercept = 0, linetype = 2) +
               geom_hline(yintercept = 10, linetype = 2) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_vline(xintercept = 10, linetype = 2) +
               annotate(geom = 'text', x = -5, y = 15, hjust = 0,
                        label = str_glue("r = {round(cor(six_3$V1, six_3$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 7.5, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_3$V2), 2)}")) +
               annotate(geom = 'text', x = -5, y = 6.5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_3$V2),2)}")) +
               annotate(geom = 'text', x = 6.5, y = -4, hjust = 0,
                        label = str_glue("Mean = {round(mean(six_3$V1), 2)}")) +
               annotate(geom = 'text', x = 6.5, y = -5, hjust = 0,
                        label = str_glue("SD = {round(sd(six_3$V1), 2)}")) +
               labs(subtitle = 'Mean = 6.2, SD = 2.2 (constrained), cor = 0.8') +
               scale_y_continuous(limits = c(-5, 15)) +
               scale_x_continuous(limits = c(-5, 15)) +
               theme(panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)))

# Linear regression
summary(lm(V2 ~ V1, data = six_3))
```

## Model mean of V1 with increasing V1 cut-offs from 0 to 5 

```{r three_cutoffV1V1}
# Extract visit 1 data 
six_3V1 <- six_3$V1

# Generate a vector of cut-off values to iterate over
cutoff <- 0:5

# Generate a vector of V1 means at each V1 cut-off
six_3V1.shift <- sapply(cutoff, function(x){mean(six_3V1[six_3V1 > x])})

# Calculate deviation 
(six_3V1.df <- data.frame(cutoff = cutoff,
                           mean = six_3V1.shift) %>% 
        mutate(deviation = mean - mean(six_3V1)))

# Plot data
ggplot(data = six_3V1.df) +
    aes(x = cutoff, y = mean, ymin = mean(six_3V1), ymax = mean) +
    geom_ribbon(alpha = 0.6) +
    geom_point(size = 3) +
    geom_line(size = 1) +
    geom_text(aes(label = round(mean, 2)), nudge_y = 1) +
    scale_y_continuous(limits = c(0, 10),
                       breaks = c(0, 2, 4, 6, 8, 10)) +
    labs(subtitle = 'Shift in V1 mean with increasing V1 NRS cut-off value',
         x = 'NRS cut-off',
         y = 'NRS mean score') +
    theme(panel.grid = element_blank(),
          plot.subtitle = element_text(size = 16))
```

## Model mean of V2 with increasing V1 cut-offs from 0 to 5 

```{r three_cutoffV1V2}
# Extract visit 2 data 
six_3V2 <- six_3$V2

# Generate a vector of cut-off values to iterate over
cutoff <- 0:5

# Generate a vector of V2 means at each V1 cut-off
six_3V2.shift <- map_dbl(.x = cutoff,
                          ~ six_3 %>% 
                              filter(V1 > .x) %>% 
                              .$V2 %>% 
                              mean(.))

# Calculate deviation
(six_3V2.df <- data.frame(cutoff = cutoff,
                           mean = six_3V2.shift) %>% 
        mutate(deviation = mean - mean(six_3V2)))

# Plot data
ggplot(data = six_3V2.df) +
    aes(x = cutoff, y = mean, ymin = mean(six_3V2), ymax = mean) +
    geom_ribbon(alpha = 0.6) +
    geom_point(size = 3) +
    geom_line(size = 1) +
    geom_text(aes(label = round(mean, 2)), nudge_y = 1) +
    scale_y_continuous(limits = c(0, 10),
                       breaks = c(0, 2, 4, 6, 8, 10)) +
    labs(subtitle = 'Shift in V2 mean with increasing V1 NRS cut-off value',
         x = 'NRS cut-off',
         y = 'NRS mean score') + 
    theme(panel.grid = element_blank(),
          plot.subtitle = element_text(size = 16))
```

## Placebo response

### threshold: 0

```{r three_threshold0}
# Process data
placebo_3.0 <- six_3 %>% 
    filter(V1 >= 0) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_3.0,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_3.0[, 1:3] %>% 
               bind_rows(six_3) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_3,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_3.0,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_3$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_3.0$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 0, linetype = 2) +
               geom_hline(yintercept = mean(six_3$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_3.0$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.5, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_3V1.df$deviation[4], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_3V2.df$deviation[4], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 1.2, cor = 0.8; Cut-off: 0') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

### threshold: 3

```{r three_threshold3}
# Process data
placebo_3.3 <- six_3 %>% 
    filter(V1 >= 3) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Set seed
set.seed(2019)

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_3.3,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_3.3[, 1:3] %>% 
               bind_rows(six_3) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_3,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_3.3,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_3$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_3.3$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 3, linetype = 2) +
               geom_hline(yintercept = mean(six_3$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_3.3$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.5, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_3V1.df$deviation[4], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_3V2.df$deviation[4], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 2.2, cor = 0.8; Cut-off: 3') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

### threshold: 4

```{r three_threshold4}
# Process that data
placebo_3.4 <- six_3 %>% 
    filter(V1 >= 4) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Set seed
set.seed(2019)

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_3.4,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_3.4[, 1:3] %>% 
               bind_rows(six_3) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_3,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_3.4,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_3$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_3.4$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 4, linetype = 2) +
               geom_hline(yintercept = mean(six_3$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_3.4$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 6.8, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_3V1.df$deviation[5], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_3V2.df$deviation[5], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 2.2, cor = 0.8; Cut-off: 4') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

### threshold: 5

```{r three_threshold5}
# Process that data 
placebo_3.5 <- six_3 %>% 
    filter(V1 >= 5) %>% 
    mutate(difference = V1 - V2) %>% 
    mutate(group = 'Cut-off')

# Set seed
set.seed(2019)

# Calculate the mean (95%CI) difference between V1 and V2
groupwiseMean(difference ~ 1,
              data = placebo_3.5,
              R = 5000,
              traditional = FALSE,
              bca = TRUE) %>% 
  kable(.)

# Plot the data
ggMarginal(placebo_3.5[, 1:3] %>% 
               bind_rows(six_3) %>% 
               mutate(group = factor(group, 
                                     levels = c('No cut-off', 'Cut-off'),
                                     ordered = TRUE)) %>% 
               ggplot(data = .) +
               aes(x = V1, y = V2) +
               geom_point(aes(colour = group, fill = group),
                          size = 1,
                          key_glyph = draw_key_rect) +
               geom_point(data = six_3,
                          colour = '#999999',
                          size = 1) +
               geom_point(data = placebo_3.5,
                          size = 1,
                          colour = '#000000') +
               geom_vline(xintercept = mean(six_3$V1),
                          colour = pal[1]) +
               geom_vline(xintercept = mean(placebo_3.5$V1),
                          colour = pal[2]) +
               geom_vline(xintercept = 5, linetype = 2) +
               geom_hline(yintercept = mean(six_3$V2),
                          colour = pal[1]) +
               geom_hline(yintercept = mean(placebo_3.5$V2),
                          colour = pal[2]) +
               annotate(geom = 'text', x = 7, y = 10, hjust = 0,
                        label = str_glue("Deviation = {round(six_3V1.df$deviation[6], 2)}pts")) +
               annotate(geom = 'text', x = 7.5, y = 5.5, hjust = 0,
                        label = str_glue("Deviation = {round(six_3V2.df$deviation[6], 2)}pts")) +
               scale_y_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_x_continuous(limits = c(0, 10),
                                  breaks = c(0, 2, 4, 6, 8, 10)) +
               scale_fill_manual(values = pal) +
               scale_colour_manual(values = pal) +
               labs(subtitle = 'Base model: Mean = 6.2, SD = 2.2, cor = 0.8; Cut-off: 5') +
               theme(legend.title = element_blank(),
                     legend.position = c(0.85, 0.15),
                     legend.background = element_rect(colour = '#000000',
                                                      size = 0.5),
                     panel.grid = element_blank(),
                     plot.subtitle = element_text(size = 16)),
           groupColour = TRUE,
           groupFill = TRUE)
```

----

# Session information 

```{r}
sessionInfo()
```