---
title: "Supplement 1"
subtitle: "Flattening of the relationship between successive pain intensity ratings"
author: "Peter Kamerman"
date: "Last knitted: `r format(Sys.Date(), '%d %B %Y')`"
---

```{r include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(MASS)
library(MBESS)
library(car)
library(patchwork)

# Set ggplot theme
theme_set(new = theme_bw(base_size = 20)) 
theme_update(legend.text = element_text(size = 14),
             axis.text = element_text(colour = '#000000',
                                      size = 20),
             axis.title = element_text(size = 20),
             panel.grid = element_blank(),
             plot.caption = element_text(size = 12),
             plot.title = element_text(size = 20),
             plot.subtitle = element_text(size = 16))

# Output options
if(!dir.exists('figures')){
  dir.create('figures')  
} 

if(!dir.exists('figures/supplement-1-flattening-of-the-regression-relationship/')){
  dir.create('figures/supplement-1-flattening-of-the-regression-relationship/')  
} 

knitr::opts_chunk$set(fig.height = 7,
               fig.width = 7,
               fig.path = 'figures/supplement-1-flattening-of-the-regression-relationship/')
```

----

# Introduction

The use of pain intensity cut-offs for study inclusion in clinical trial (typically a lower cut-off of 4/10 on an 11-point numerical pain rating scale) has two consequences. Firstly, the cut-off artificially raises the baseline mean pain score of the sample above that of the mean score of the population from which the sample was drawn. Secondly, unless the correlation between two sequential measurements is 1, there should be a "flattening" of the relationship between the first and subsequent measurements. This "flattening" means that the cut-off has a disproportionate effect on the mean baseline pain intensity compared to subsequent measurements. 

This script demonstrates the "flattening" of the relationship between two sequential pain measurements in a hypothetical placebo group in a clinical trial for the management of neuropathic pain, in the absence of any cut-off. For both the baseline and subsequent measurement (V1 and V2, respectively), the mean pain intensity was set at 6.2 (SD 1.7); typical baseline center and spread values for placebo groups in placebo-controlled trials for the management of neuropathic pain when there is no cut-off inclusion criterion (see Supplement 2). By using the same mean (SD) pain intensity for both measurements I have assumed that the pain is, on average, stable over the time period between the two measurements. 

For the purposes of this simulation, I examined the relationship between the two measurements (V1 and V2) over a range of correlation values, namely: _r_ = 1.0, 0.8, 0.5, and 0.2. 

Also, I constructed the models under two conditions: _constrained_ and _unconstrained_ pain intensity ratings. For the _unconstrained_ models I took the raw values obtained through sampling from a bivariate normal distribution. Thereafter, values were filtered (_constrained_) such that the minimum V1 value was 1 and the minimum V2 value was 0 on an 11-point NRS, and the maximum V1 and V2 values were 10 on an 11-point NRS. The minimum value of V1 was set to 1 because volunteers eligible to enter a placebo-controlled clinical trial can be expected to have at least some pain. In comparison, V2 values were unconstrained and could take any value from 0 to 10 because pain intensity may take values across the full range of the scale on follow-up. Maximum pain rating were limited to values of 10, the upper limit of the rating scale. 

For reproducibility, I set the random seed to _"2019"_ for all random sampling procedures.

Note: Because of random sampling the mean (SD) of the samples differ slightly from the population mean (SD).

----

# Generate 2x2 covariance matrices 

Generate covariance matrices using an SD of 1.7 and correlation of _r_ = 1.0, 0.8, 0.5, and 0.2.

```{r cov_matrix}
# Generate 2*2 correlation matrices
cor_10 <- matrix(c(1, 1, 1, 1), ncol = 2)
cor_08 <- matrix(c(1, 0.8, 0.8, 1), ncol = 2)
cor_05 <- matrix(c(1, 0.5, 0.5, 1), ncol = 2)
cor_02 <- matrix(c(1, 0.2, 0.2, 1), ncol = 2)

# Set the standard deviation
std <- c(1.7, 1.7)

# Generate 2*2 covariance matrices using the correlation matrices and SD
cov_10 <- cor2cov(cor.mat = cor_10,
                  sd = std)
cov_10
cov_08 <- cor2cov(cor.mat = cor_08,
                  sd = std)
cov_08
cov_05 <- cor2cov(cor.mat = cor_05,
                  sd = std)
cov_05
cov_02 <- cor2cov(cor.mat = cor_02,
                  sd = std)
cov_02
```

----

# Correlation: r = 1.0

## Unconstrained data

```{r 10_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data (1000 pairs from a bivariate normal distribution)
cor_10.base <- as.data.frame(mvrnorm(n = 1000, mu = c(6.2, 6.2), Sigma = cov_10))

# Plot unconstrained data
ggplot(data = cor_10.base) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_10.base$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_10.base$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_10.base$V1, 
                              cor_10.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 14, hjust = 0, size = 5,
             label = str_glue("n = {round(nrow(cor_10.base))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.base$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_10.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.base$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_10.base$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_10.base$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_10.base$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_10.base$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_10.base$V1), 2)}")) +
    labs(title = 'A: Unconstained',
         caption = 'Population parameters: Mean = 6.2, SD = 1.7, r = 1.0') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme(plot.caption = element_text(size = 14))

# Linear regression
summary(lm(V2 ~ V1, data = cor_10.base))
Confint(lm(V2 ~ V1, data = cor_10.base))
```

## Constrained data

```{r 10_constrained}
# Constrain data
cor_10.constrained <- cor_10.base %>%
    filter(V1 >= 1 & V1 <= 10) %>% 
    filter(V2 >= 0 & V2 <= 10) %>% 
    mutate(group = 'No threshold')

# Plot constrained data
ggplot(data = cor_10.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_10.constrained$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_10.constrained$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_10.constrained$V1, 
                                         cor_10.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 14, hjust = 0, size = 5,
             label = str_glue("n = {round(nrow(cor_10.constrained))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.constrained$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_10.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.constrained$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_10.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_10.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5, 
             label = str_glue("Mean = {round(mean(cor_10.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_10.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_10.constrained$V1), 2)}")) +
    labs(title = 'B: Constrained',
         caption = 'Population parameters: Mean = 6.2, SD = 1.7, r = 1.0') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme(plot.caption = element_text(size = 14))
  
# Linear regression
summary(lm(V2 ~ V1, data = cor_10.constrained))
Confint(lm(V2 ~ V1, data = cor_10.constrained))
```

----

# Correlation: r = 0.8

## Unconstrained data

```{r 08_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data (1000 pairs from a bivariate normal distribution)
cor_08.base <- as.data.frame(mvrnorm(n = 1000, mu = c(6.2, 6.2), Sigma = cov_08))

# Plot unconstrained data
ggplot(data = cor_08.base) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_08.base$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_08.base$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_08.base$V1, 
                              cor_08.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 14, hjust = 0, size = 5,
             label = str_glue("n = {round(nrow(cor_08.base))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.base$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_08.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.base$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_08.base$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_08.base$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_08.base$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_08.base$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_08.base$V1), 2)}")) +
    labs(title = 'A: Unconstained',
         caption = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.8') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme(plot.caption = element_text(size = 14))

# Linear regression
summary(lm(V2 ~ V1, data = cor_08.base))
Confint(lm(V2 ~ V1, data = cor_08.base))
```

## Constrained data

```{r 08_constrained}
# Constrain data
cor_08.constrained <- cor_08.base %>%
    filter(V1 >= 1 & V1 <= 10) %>% 
    filter(V2 >= 0 & V2 <= 10) %>%
    mutate(group = 'No threshold')

# Plot constrained data
ggplot(data = cor_08.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_08.constrained$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_08.constrained$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_08.constrained$V1, 
                              cor_08.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 14, hjust = 0, size = 5,
             label = str_glue("n = {round(nrow(cor_08.constrained))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.constrained$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_08.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.constrained$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_08.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_08.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5, 
             label = str_glue("Mean = {round(mean(cor_08.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_08.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_08.constrained$V1), 2)}")) +
    labs(title = 'B: Constrained',
         caption = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.8') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme(plot.caption = element_text(size = 14))
  
# Linear regression
summary(lm(V2 ~ V1, data = cor_08.constrained))
Confint(lm(V2 ~ V1, data = cor_08.constrained))
```

----

# Correlation: r = 0.5

## Unconstrained data

```{r 05_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data (1000 pairs from a bivariate normal distribution)
cor_05.base <- as.data.frame(mvrnorm(n = 1000, mu = c(6.2, 6.2), Sigma = cov_05))

# Plot unconstrained data
ggplot(data = cor_05.base) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_05.base$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_05.base$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_05.base$V1, 
                              cor_05.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 14, hjust = 0, size = 5,
             label = str_glue("n = {round(nrow(cor_05.base))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.base$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_05.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.base$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_05.base$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_05.base$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_05.base$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_05.base$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_05.base$V1), 2)}")) +
    labs(title = 'A: Unconstained',
         caption = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.5') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme(plot.caption = element_text(size = 14))

# Linear regression
summary(lm(V2 ~ V1, data = cor_05.base))
Confint(lm(V2 ~ V1, data = cor_05.base))
```

## Constrained data

```{r 05_constrained}
# Constrain data
cor_05.constrained <- cor_05.base %>%
    filter(V1 >= 1 & V1 <= 10) %>% 
    filter(V2 >= 0 & V2 <= 10) %>% 
    mutate(group = 'No threshold')

# Plot constrained data
ggplot(data = cor_05.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_05.constrained$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_05.constrained$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_05.constrained$V1, 
                              cor_05.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 14, hjust = 0, size = 5,
             label = str_glue("n = {round(nrow(cor_05.constrained))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.constrained$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_05.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.constrained$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_05.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_05.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5, 
             label = str_glue("Mean = {round(mean(cor_05.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_05.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_05.constrained$V1), 2)}")) +
    labs(title = 'B: Constrained',
         caption = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.5') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme(plot.caption = element_text(size = 14))
  
# Linear regression
summary(lm(V2 ~ V1, data = cor_05.constrained))
Confint(lm(V2 ~ V1, data = cor_05.constrained))
```

----

# Correlation: r = 0.2

## Unconstrained data

```{r 02_base}
# Set the random seed for reproducibility
set.seed(2019)

# Generate the data
cor_02.base <- as.data.frame(mvrnorm(n = 1000, mu = c(6.2, 6.2), Sigma = cov_02))

# Plot unconstrained data
ggplot(data = cor_02.base) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_02.base$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_02.base$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_02.base$V1, 
                              cor_02.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 14, hjust = 0, size = 5,
             label = str_glue("n = {round(nrow(cor_02.base))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.base$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_02.base$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.base$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_02.base$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_02.base$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_02.base$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_02.base$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_02.base$V1), 2)}")) +
    labs(title = 'A: Unconstained',
         caption = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.2') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme(plot.caption = element_text(size = 14))

# Linear regression
summary(lm(V2 ~ V1, data = cor_02.base))
Confint(lm(V2 ~ V1, data = cor_02.base))
```

## Constrained data

```{r 02_constrained}
# Constrain data
cor_02.constrained <- cor_02.base %>%
    filter(V1 >= 1 & V1 <= 10) %>% 
    filter(V2 >= 0 & V2 <= 10) %>% 
    mutate(group = 'No threshold')

# Plot constrained data
ggplot(data = cor_02.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE) +
    geom_hline(yintercept = mean(cor_02.constrained$V2), 
               colour = 'red', size = 1) +
    geom_vline(xintercept = mean(cor_02.constrained$V1), 
               colour = 'red', size = 1) +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 5,
             label = str_glue("r = {round(cor(cor_02.constrained$V1, 
                              cor_02.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 14, hjust = 0, size = 5,
             label = str_glue("n = {round(nrow(cor_02.constrained))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.constrained$V2) + 1.7, 
             hjust = 0, size = 5,
             label = str_glue("Mean = {round(mean(cor_02.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.constrained$V2) + 0.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_02.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_02.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 5, 
             label = str_glue("Mean = {round(mean(cor_02.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_02.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 5,
             label = str_glue("SD = {round(sd(cor_02.constrained$V1), 2)}")) +
    labs(title = 'B: Constrained',
         caption = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.2') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme(plot.caption = element_text(size = 14))
  
# Linear regression
summary(lm(V2 ~ V1, data = cor_02.constrained))
Confint(lm(V2 ~ V1, data = cor_02.constrained))
```

----

# Publication plots

The output of the code is plotted to a 'PNG' graphics file.

```{r pub_plot}
# r = 1.0
plot_1 <- ggplot(data = cor_10.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE, 
                size = 1.5) +
    geom_hline(yintercept = mean(cor_10.constrained$V2), 
               colour = 'red') +
    geom_vline(xintercept = mean(cor_10.constrained$V1), 
               colour = 'red') +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 6,
             label = str_glue("r = {round(cor(cor_10.constrained$V1, 
                                         cor_10.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 13.7, hjust = 0, size = 6,
             label = str_glue("n = {round(nrow(cor_10.constrained))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.constrained$V2) + 1.7, 
             hjust = 0, size = 4,
             label = str_glue("Mean = {round(mean(cor_10.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_10.constrained$V2) + 0.75, 
             hjust = 0, size = 4,
             label = str_glue("SD = {round(sd(cor_10.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_10.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 4, 
             label = str_glue("Mean = {round(mean(cor_10.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_10.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 4,
             label = str_glue("SD = {round(sd(cor_10.constrained$V1), 2)}")) +
    labs(subtitle = 'Population parameters: Mean = 6.2, SD = 1.7, r = 1.0') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme_bw(base_size = 18) +
    theme(axis.text = element_text(colour = '#000000'),
          axis.title.x = element_blank(),
          panel.grid = element_blank(),
          plot.subtitle = element_text(size = 14))
  
# r = 0.8
plot_2 <- ggplot(data = cor_08.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE, 
                size = 1.5) +
    geom_hline(yintercept = mean(cor_08.constrained$V2), 
               colour = 'red') +
    geom_vline(xintercept = mean(cor_08.constrained$V1), 
               colour = 'red') +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 6,
             label = str_glue("r = {round(cor(cor_08.constrained$V1, 
                              cor_08.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 13.7, hjust = 0, size = 6,
             label = str_glue("n = {round(nrow(cor_08.constrained))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.constrained$V2) + 1.7, 
             hjust = 0, size = 4,
             label = str_glue("Mean = {round(mean(cor_08.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_08.constrained$V2) + 0.75, 
             hjust = 0, size = 4,
             label = str_glue("SD = {round(sd(cor_08.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_08.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 4, 
             label = str_glue("Mean = {round(mean(cor_08.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_08.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 4,
             label = str_glue("SD = {round(sd(cor_08.constrained$V1), 2)}")) +
    labs(subtitle = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.8') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme_bw(base_size = 18) +
    theme(axis.text = element_text(colour = '#000000'),
          axis.title = element_blank(),
          panel.grid = element_blank(),
          plot.subtitle = element_text(size = 14))
  
# r = 0.5
plot_3 <- ggplot(data = cor_05.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE,
                size = 1.5) +
    geom_hline(yintercept = mean(cor_05.constrained$V2), 
               colour = 'red') +
    geom_vline(xintercept = mean(cor_05.constrained$V1), 
               colour = 'red') +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 6,
             label = str_glue("r = {round(cor(cor_05.constrained$V1, 
                              cor_05.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 13.7, hjust = 0, size = 6,
             label = str_glue("n = {round(nrow(cor_05.constrained))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.constrained$V2) + 1.7, 
             hjust = 0, size = 4,
             label = str_glue("Mean = {round(mean(cor_05.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_05.constrained$V2) + 0.75, 
             hjust = 0, size = 4,
             label = str_glue("SD = {round(sd(cor_05.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_05.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 4, 
             label = str_glue("Mean = {round(mean(cor_05.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_05.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 4,
             label = str_glue("SD = {round(sd(cor_05.constrained$V1), 2)}")) +
    labs(subtitle = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.5') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme_bw(base_size = 18) +
    theme(axis.text = element_text(colour = '#000000'),
          panel.grid = element_blank(),
          plot.subtitle = element_text(size = 14))
  
# r = 0.2
plot_4 <- ggplot(data = cor_02.constrained) +
    aes(x = V1, y = V2) + 
    geom_point() + 
    geom_abline(slope = 1, intercept = 0) +
    geom_smooth(method = 'lm',
                se = FALSE,
                size = 1.5) +
    geom_hline(yintercept = mean(cor_02.constrained$V2), 
               colour = 'red') +
    geom_vline(xintercept = mean(cor_02.constrained$V1), 
               colour = 'red') +
    geom_rect(ymin = 0, ymax = 10, 
              xmin = 0, xmax = 10, 
              colour = '#000000',
              alpha = 0,
              linetype = 2) +
    annotate(geom = 'text', x = -5, y = 15, hjust = 0, size = 6,
             label = str_glue("r = {round(cor(cor_02.constrained$V1, 
                              cor_02.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = 13.7, hjust = 0, size = 6,
             label = str_glue("n = {round(nrow(cor_02.constrained))}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.constrained$V2) + 1.7, 
             hjust = 0, size = 4,
             label = str_glue("Mean = {round(mean(cor_02.constrained$V2), 2)}")) +
    annotate(geom = 'text', x = -5, y = mean(cor_02.constrained$V2) + 0.75, 
             hjust = 0, size = 4,
             label = str_glue("SD = {round(sd(cor_02.constrained$V2),2)}")) +
    annotate(geom = 'text', x = mean(cor_02.constrained$V1) + 0.2, y = -3.8, 
             hjust = 0, size = 4, 
             label = str_glue("Mean = {round(mean(cor_02.constrained$V1), 2)}")) +
    annotate(geom = 'text', x = mean(cor_02.constrained$V1) + 0.2, y = -4.75, 
             hjust = 0, size = 4,
             label = str_glue("SD = {round(sd(cor_02.constrained$V1), 2)}")) +
    labs(subtitle = 'Population parameters: Mean = 6.2, SD = 1.7, r = 0.2') +
    scale_y_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    scale_x_continuous(limits = c(-5, 15),
                       breaks = c(0, 5, 10)) +
    theme_bw(base_size = 18) +
    theme(axis.text = element_text(colour = '#000000'),
          axis.title.y = element_blank(),
          panel.grid = element_blank(),
          plot.subtitle = element_text(size = 14))

# Patchwork
patch <- plot_1 + plot_2 + plot_3 + plot_4 + 
  plot_layout(ncol = 2) + plot_annotation(tag_levels = 'A')

ggsave(filename = 'figures/figure-regression-lines.png',
       plot = patch,
       width = 11.5,
       height = 11.5)
```

----

# Session information 

```{r}
sessionInfo()
```

