---
title: "Supplement 2"
subtitle: "Baseline characteristics of RCTs for neuropathic pain"
author: "Peter Kamerman"
date: "Last knitted: `r format(Sys.Date(), '%d %B %Y')`"
---

```{r set_up, include = FALSE}
# Load packages
library(tidyverse)
library(spatstat)

# Output options
if(!dir.exists('figures')){
  dir.create('figures')  
} 

if(!dir.exists('figures/supplement-2-baseline-calculations/')){
  dir.create('figures/supplement-2-baseline-calculations/')  
} 

# Set options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.height = 5,
                      fig.width = 7, 
                      fig.path = 'figures/supplement-2-baseline-calculations/')
```

----

# Pain intensity inclusion thresholds

- Original data source: Finnerup et al 2015, Appendix 4[^1].

    - All numeric values were used (after removing duplicate entries).

    - All visual analogue values were converted to a 0 to 10 scale.

[^1]: Finnerup NB, Attal N, Haroutounian S, McNicol E, Baron R, Dworkin RH, Gilron I, Haanpää M, Hansson P, Jensen TS, Kamerman PR, Lund K, Moore A, Raja SN, Rice ASC, Rowbotham M, Sena E, Siddall P, Smith BH, Wallace M. Pharmacotherapy for neuropathic pain in adults: a systematic review and meta-analysis. Lancet Neurol 2015;14:162–173. doi:10.1016/S1474-4422(14)70251-0

```{r thresholds}
# Inclusion criteria thresholds extracted from the supplementary 
# materials of Finnerup et al., 2015
cut_off <- c(5, 4, 4, 2, 4, 3, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
             4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
             4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 3, 4, 
             4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 4, 4, 4, 3, 5, 4, 4, 4, 5, 5,
             4, 4, 5, 3, 4, 4, 4, 5, 4, 3, 3, 3, 3, 3, 3, 3, 4, 7, 5, 4, 3, 2,
             3, 4, 4, 2.5, 2.5, 4, 4, 4, 4, 5, 4, 4, 8, 4, 4, 4, 5, 3, 4, 4, 4)

# Generate summary statistics
## 6-number summary
summary(cut_off)

## Tabular summary of inclusion thresholds
data.frame(cutoff = cut_off) %>% 
    group_by(cutoff) %>% 
    summarise(count = n(),
              percent = round(100 * (count/length(cut_off)), 1)) %>% 
    knitr::kable(., caption = 'Summary of pain inclusion thresholds')
```

----

# Explore baseline pain intensity data

## Import data

- Original data source: Finnerup et al 2015, Appendix 4$^1$,

```{r import data}
data <- read_csv('data/baseline-data.csv')
```

## Explore data 

### Median

```{r median_explore}
data %>% 
    filter(mean_or_median == 'median') %>% 
    summarise(min = round(min(value, na.rm = TRUE), 1),
              Q25 = round(quantile(value, probs = 0.25, na.rm = TRUE), 1),
              mean = round(mean(value, na.rm = TRUE), 1),
              median = round(median(value, na.rm = TRUE), 1),
              Q75 = round(quantile(value, probs = 0.75, na.rm = TRUE), 1),
              max = round(max(value, na.rm = TRUE), 1)) %>% 
    knitr::kable(., caption = 'Summary: median values')
```

### Mean

```{r mean_explore}
data %>% 
    filter(mean_or_median == 'mean') %>% 
    summarise(min = round(min(value, na.rm = TRUE), 1),
              Q25 = round(quantile(value, probs = 0.25, na.rm = TRUE), 1),
              mean = round(mean(value, na.rm = TRUE), 1),
              median = round(median(value, na.rm = TRUE), 1),
              Q75 = round(quantile(value, probs = 0.75, na.rm = TRUE), 1),
              max = round(max(value, na.rm = TRUE), 1)) %>% 
    knitr::kable(., caption = 'Summary: mean values')
```

### SD

```{r sd_explore}
data %>% 
    filter(!is.na(sd)) %>% 
    summarise(min = round(min(sd, na.rm = TRUE), 1),
              Q25 = round(quantile(sd, probs = 0.25, na.rm = TRUE), 1),
              mean = round(mean(sd, na.rm = TRUE), 1),
              median = round(median(sd, na.rm = TRUE), 1),
              Q75 = round(quantile(sd, probs = 0.75, na.rm = TRUE), 1),
              max = round(max(sd, na.rm = TRUE), 1)) %>% 
    knitr::kable(., caption = 'Range of SD values')
```

----

# Weighted medians 

- Three studies, four median values.

- Hahn et al., 2004 (active), Hahn et al., 2004 (placebo), Yuen et al., 2002, Low et al., 1995

```{r median}
# Process data
median <- data %>% 
    filter(included_in_analysis == 'yes') %>% 
    filter(mean_or_median == 'median') %>% 
    # Calculate total sample size
    mutate(total_sample = sum(sample_size)) %>% 
    # Calculate weights
    mutate(weights = sample_size / total_sample)
    
## Weighted median
weighted.median(x = median$value, 
                w = median$weights)
```

----

# Pooled mean

- Formula sourced from: https://www.ncbi.nlm.nih.gov/books/NBK56512/

```{r pooled_mean}
# Process data
mean <- data %>% 
    filter(included_in_analysis == 'yes') %>% 
    filter(mean_or_median == 'mean') %>% 
    # Multiply mean by the sample size
    mutate(mean_by_n = value * sample_size) 

# Pooled mean
sum(mean$mean_by_n) / sum(mean$sample_size)
```

----

# Pooled SD

- Formula sourced from: https://www.ncbi.nlm.nih.gov/books/NBK56512/

```{r pooled_sd}
# Process data
sd <- data %>% 
    filter(included_in_analysis == 'yes') %>% 
    filter(mean_or_median == 'mean') %>% 
    filter(!is.na(sd)) %>% 
    # Square the SD
    mutate(SD_squared = sd^2) %>% 
    # Calculate sample size -1
    mutate(n_minus_1 = sample_size - 1) %>% 
    # Get the number of groups
    mutate(k = length(unique(.$authors))) %>% 
    # Calculate (n-1)SD^2
    mutate(numerator = SD_squared * n_minus_1)

# Pooled SD
sqrt(sum(sd$numerator) / (sum(sd$sample_size) - sd$k[[1]]))
```

----

# Session information

```{r session_info}
sessionInfo()
```